theme: jekyll-theme-hacker
title: manas3c:~#
description: TRY Harder!
show_downloads: false
show_repo: false

gems:
- jekyll-sitemap

whitelist:
- jekyll-sitemap

socialIcons:
    - name: twitter
      url: "https://twitter.com/manas3c"
    - name: github
      url: "https://github.com/manas3c"
    - name: discord
      url: "manas3#1138"
